import { Colors, Radius, Spacing, TouchTarget } from '@/shared/theme/tokens';
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: Colors.light.background,
  },
  topBar: {
    minHeight: 60,
    paddingHorizontal: Spacing.three,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
  },
  iconButton: {
    width: TouchTarget,
    height: TouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.medium,
    borderWidth: 1,
    borderColor: Colors.light.border,
    backgroundColor: Colors.light.surface,
  },
  titleCopy: {
    flex: 1,
  },
  title: {
    fontSize: 23,
    lineHeight: 29,
    fontWeight: '800',
    color: Colors.light.text,
  },
  subtitle: {
    marginTop: Spacing.half,
    fontSize: 13,
    fontWeight: '700',
    color: Colors.light.textSecondary,
  },
  browseActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  actionButton: {
    minHeight: TouchTarget,
    paddingHorizontal: Spacing.three,
    borderRadius: Radius.medium,
    backgroundColor: Colors.light.accent,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.two,
  },
  actionButtonDisabled: {
    opacity: 0.42,
  },
  actionButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: Colors.light.surface,
  },
  pressed: {
    opacity: 0.72,
  },
  disabledControl: {
    opacity: 0.48,
  },
  loadingOverlay: {
    ...StyleSheet.absoluteFill,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.three,
    backgroundColor: 'rgba(245,247,250,0.72)',
  },
  loadingCard: {
    minWidth: 156,
    minHeight: 72,
    borderRadius: Radius.medium,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.two,
  },
  loadingText: {
    fontSize: 13,
    fontWeight: '800',
  },
  sortHeaderButton: {
    width: TouchTarget,
    height: TouchTarget,
    borderRadius: Radius.medium,
    borderWidth: 1,
    borderColor: Colors.light.border,
    backgroundColor: Colors.light.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sortModalLayer: {
    flex: 1,
  },
  sortCard: {
    position: 'absolute',
    borderRadius: Radius.medium,
    borderWidth: 1,
    borderColor: Colors.light.border,
    backgroundColor: Colors.light.surface,
    padding: Spacing.two,
    gap: Spacing.one,
  },
  sortTitle: {
    paddingHorizontal: Spacing.two,
    paddingVertical: Spacing.one,
    fontSize: 18,
    fontWeight: '800',
    color: Colors.light.text,
  },
  sortOption: {
    minHeight: TouchTarget,
    borderRadius: Radius.small,
    paddingHorizontal: Spacing.two,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  sortOptionIcon: {
    width: 18,
    height: 18,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sortOptionText: {
    fontSize: 15,
    fontWeight: '800',
    color: Colors.light.text,
  },
  sortSeparator: {
    height: 1,
    marginVertical: Spacing.one,
    backgroundColor: Colors.light.border,
  },
  listSection: {
    flex: 1,
    minHeight: 0,
  },
  fixedSectionHeader: {
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.two,
    paddingBottom: Spacing.two,
    gap: Spacing.one,
  },
  scrollList: {
    flex: 1,
  },
  listContent: {
    paddingHorizontal: Spacing.three,
    paddingTop: Spacing.one,
    paddingBottom: Spacing.three,
    gap: Spacing.three,
  },
  sectionTitle: {
    fontSize: 18,
    lineHeight: 24,
    fontWeight: '800',
    color: Colors.light.text,
  },
  browserTitleRow: {
    minHeight: TouchTarget,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.two,
  },
  browserMeta: {
    fontSize: 13,
    fontWeight: '700',
    color: Colors.light.textSecondary,
  },
  directoryCard: {
    minHeight: 108,
    borderRadius: Radius.medium,
    borderWidth: 1,
    borderColor: Colors.light.border,
    backgroundColor: Colors.light.surface,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  directoryMain: {
    flex: 1,
    minHeight: 108,
    padding: Spacing.three,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.three,
  },
  directoryIcon: {
    width: 52,
    height: 52,
    borderRadius: Radius.medium,
    borderWidth: 1,
    borderColor: Colors.light.border,
    backgroundColor: Colors.light.backgroundElement,
    alignItems: 'center',
    justifyContent: 'center',
  },
  directoryCopy: {
    flex: 1,
    gap: Spacing.one,
  },
  directoryName: {
    fontSize: 17,
    lineHeight: 22,
    fontWeight: '800',
    color: Colors.light.text,
  },
  directoryUrl: {
    fontSize: 13,
    lineHeight: 18,
    color: Colors.light.textSecondary,
  },
  directoryMeta: {
    fontSize: 12,
    fontWeight: '700',
    color: Colors.light.accent,
  },
  directoryActions: {
    width: 64,
    minHeight: 108,
    borderLeftWidth: 1,
    borderLeftColor: Colors.light.border,
  },
  cardIconButton: {
    flex: 1,
    minHeight: 56,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.light.surface,
  },
  dangerIconButton: {
    borderTopWidth: 1,
    borderTopColor: Colors.light.border,
  },
  entry: {
    minHeight: 64,
    borderRadius: Radius.medium,
    borderWidth: 1,
    borderColor: Colors.light.border,
    backgroundColor: Colors.light.surface,
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: Spacing.two,
  },
  checkboxTouch: {
    width: 44,
    minHeight: 64,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxBox: {
    width: 22,
    height: 22,
    borderRadius: 3,
    borderWidth: 2,
    borderColor: Colors.light.accent,
    backgroundColor: Colors.light.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checkboxBoxSelected: {
    backgroundColor: Colors.light.accent,
  },
  entryMain: {
    flex: 1,
    minHeight: 64,
    paddingVertical: Spacing.two,
    paddingLeft: Spacing.one,
    paddingRight: Spacing.three,
    flexDirection: 'row',
    alignItems: 'center',
    gap: Spacing.two,
  },
  entryCopy: {
    flex: 1,
    gap: Spacing.half,
  },
  autoTextViewport: {
    width: '100%',
    overflow: 'hidden',
  },
  autoTextMeasure: {
    position: 'absolute',
    opacity: 0,
    left: 0,
    top: 0,
    zIndex: -1,
    flexShrink: 0,
    width: 10000,
  },
  autoTextContent: {
    alignSelf: 'flex-start',
    flexShrink: 0,
  },
  entryName: {
    fontSize: 16,
    lineHeight: 21,
    fontWeight: '800',
    color: Colors.light.text,
  },
  entryMeta: {
    fontSize: 11,
    lineHeight: 15,
    fontWeight: '700',
    color: Colors.light.textSecondary,
  },
  empty: {
    minHeight: 160,
    alignItems: 'center',
    justifyContent: 'center',
    gap: Spacing.three,
    padding: Spacing.four,
  },
  emptyText: {
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
    color: Colors.light.textSecondary,
  },
  modalBackdrop: {
    flex: 1,
    padding: Spacing.three,
    backgroundColor: 'rgba(20,25,35,0.26)',
    justifyContent: 'center',
  },
  modalCard: {
    borderRadius: Radius.medium,
    borderWidth: 1,
    borderColor: Colors.light.border,
    backgroundColor: Colors.light.surface,
    padding: Spacing.three,
    gap: Spacing.three,
  },
  modalHeader: {
    minHeight: TouchTarget,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  modalTitle: {
    fontSize: 20,
    lineHeight: 25,
    fontWeight: '800',
    color: Colors.light.text,
  },
  modalClose: {
    width: TouchTarget,
    height: TouchTarget,
    marginRight: -13,
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputGroup: {
    gap: Spacing.two,
  },
  label: {
    fontSize: 14,
    fontWeight: '700',
    color: Colors.light.text,
  },
  input: {
    minHeight: TouchTarget,
    borderRadius: Radius.medium,
    borderWidth: 1,
    borderColor: Colors.light.border,
    paddingHorizontal: Spacing.three,
    fontSize: 16,
    color: Colors.light.text,
  },
  modalActions: {
    minHeight: TouchTarget,
    flexDirection: 'row',
    alignItems: 'stretch',
    gap: Spacing.two,
  },
  testButton: {
    minWidth: 72,
    minHeight: TouchTarget,
    borderRadius: Radius.medium,
    borderWidth: 1,
    borderColor: Colors.light.border,
    backgroundColor: Colors.light.surface,
    alignItems: 'center',
    justifyContent: 'center',
  },
  testButtonText: {
    fontSize: 15,
    fontWeight: '800',
    color: Colors.light.text,
  },
  saveButton: {
    flex: 1,
    minHeight: TouchTarget,
    borderRadius: Radius.medium,
    backgroundColor: Colors.light.accent,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveButtonText: {
    fontSize: 16,
    fontWeight: '800',
    color: Colors.light.surface,
  },
});
